name: CI Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo Hello, world!
      - name: Build
        run: script/build
      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
